### ISSUE TITLE
Add REST debug endpoint

### ISSUE THREAD

**Issue by mephinet** [gentics/mesh-incubator#220]
Currently, in order to analyze issues in Gentics Mesh, you need to have access to the server, so that you can read the logs and the configuration files. If would be useful to have a single REST endpoint that provides a database dump in combination with the config and the logs - in a consistent and non-blocking way of course...

**Comment by Jotschi** [comment]
We already had something like this planned:

https://github.com/gentics/mesh/commit/840b10f20b67531ac1d08664a0bc555ae6652aff

* Plugin which allows access to server data.
* Docker container which will be deployed next to the supported container.

**Comment by Jotschi** [comment]
The debug info endpoint has been added in 1.1.0
